= Integrations & Other Components
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/02.other/02.other.md
:page-opendocs-slug:  /releasenotes/other

[#_release_notes_for_integration_modules_plug_ins_other_components]
== Release Notes for Integration Modules, Plug-Ins, Other Components

[#_github_actions]
=== Github Actions

* Github actions for vulnerability scanning now published at https://github.com/neuvector/neuvector-image-scan-action.

[#_helm_chart_189]
=== Helm Chart 1.8.9

* Helm chart v1.8.9 is published for 5.0.0 deployments. If using this with the preview version of 5.0.0 the following changes should be made to values.yml:
** Update the registry to docker.io
** Update image names/tags to the preview version on Docker hub
** Leave the imagePullSecrets empty

[#_splunk_app_published]
=== Splunk App Published

* New Splunk app for {product-name} is published at https://splunkbase.splunk.com/app/6205/

[#_helm_chart_update_187]
=== Helm Chart Update 1.8.7

* Support affinity and toleration customization for controller, scanner and manager.
* Add nodeSelector support for Controller, Manager, Scanner, updater pods.
* Support user-defined environment variables for controller container.

[#_community_operator_v127_for_helm_chart_182]
=== Community Operator v1.2.7 for Helm Chart 1.8.2

* Allow users to specify {product-name} release version
* Deploys latest scanner CVE db version
* Container operator image location moved to registry.neuvector.com/public
* {product-name} instance name defaults to neuvector (before it was example-neuvector)
* Updated readme document on install page and added link to release notes

[#_helm_chart_182]
=== Helm Chart 1.8.2

* Add controller ingress and route host options.

[#_certified_operator_v128_for_product_v431]
=== Certified Operator v1.2.8 for {product-name} v4.3.1

* Supports helm chart version 1.8.2
* Deploys {product-name} version 4.3.1
* Deploys scanner db version 2.360
* other changes from previous 1.2.7 version
** neuvector instance name defaults to neuvector, before it was example-neuvector
** updated readme document on install page
** corrected {product-name} logo display issue
* Known issues
** upgrading from 1.2.7 to 1.2.8 does not upgrade scanner db
work around: update scanner image to registry.connect.redhat.com/neuvector/scanner@sha256:a802c012eee80444d9deea8c4402a1d977cf57d7b2b2044f90c9acc0e7ca3e06 on scanner deployment
** readme document on install page not aligned properly
** scanner db is not updated by updater

[#_helm_chart_update_180_july_2021]
=== Helm Chart update 1.8.0 July 2021

* Helm Chart  v1.8.0 is updated to default to registry.neuvector.com as the default registry. NOTE: Must specify the version tag manually.
* Add configurable parameters such as Controller API annotations in Helm chart. Available from version 1.7.6+.
* Community Operator 1.2.6, Certified Operator 1.2.7 updated to reflect Helm chart updates including adding OpenShift route when controller.apisvc.type is enabled.

[#_other_integrations_july_2021]
=== Other Integrations July 2021

* Add HTML output format for scan results in Jenkins pipeline scanning results.
* Add namespace of impacted workload in Prometheus exporter alerts. Now supported in neuvector/prometheus-exporter:4.2.2 and later.

[#_helm_chart_update_175_may_2021]
=== Helm Chart update 1.7.5 May 2021

* Support changes required for new image registry registry.neuvector.com.  Change to this will result in image paths (ie remove neuvector from path from neuvector/controller to controller).

[#_helm_chart_update_172_april_2021]
=== Helm Chart update 1.7.2 April 2021

* Add support for separate component resources requests and limits, e.g. Controller, Enforcer cpu, memory requests.

[#_jenkins_plug_in_update_v113_april_2021]
=== Jenkins Plug-In Update v1.13 April 2021

* Fix the scan error that exists when multiple scanners are running at the same time.
* Show the Red Hat vulnerability rating in the scan result for Red Hat based images.

[#_operator_updates_april_2021]
=== Operator Updates April 2021

* OpenShift operator/helm to be able to replace self-signed certificates. Helm Chart is 1.7.1. Community Operator is 1.2.4, and Certified Operator is 1.2.3.

[#_jenkins_plug_in_v112_march_2021]
=== Jenkins Plug-In v1.12 March 2021

* Overwrite vulnerability severity by score. Be able to edit what vulnerability (CVE) score range is used for High and Medium classifications. This enables customizing what score can be used to fail builds in the pipeline.
* Add error messages to the JAVA exceptions hudson.AbortException. Enable better error message reporting from {product-name} when an error occurs.

[#_update_helm_chart_to_171_march_2021]
=== Update Helm Chart to 1.7.1 March 2021

* Add manager service loadbalancer ip and annotations.
* Add setting to set pvc capacity.
* Add runtime socket settings for k3s and AWS bottlerocket.
* Add settings to replace controller and manager certificates.

[#_scanner_february_2021]
=== Scanner February 2021

* Fix CVE-2020-1938 not discovered during scan in scanner versions 1.191 and earlier. Update to latest scanner version after 1.191.

[#_jenkins_plug_in_v111_february_2021]
=== Jenkins Plug-In v1.11 February 2021

[#_enhancements]
==== Enhancements

* Add support for deploying the stand alone {product-name} scanner. This does not require a controller and must be deployed on the same host as the Jenkins installation. Docker must also be installed on the host. Currently, only the Linux version of Jenkins is supported (not container version). Also, add _jenkins_ user to the _docker_ group.

[,bash]
----
sudo usermod -aG docker jenkins
----

References:
https://plugins.jenkins.io/neuvector-vulnerability-scanner/
https://github.com/jenkinsci/neuvector-vulnerability-scanner-plugin/releases/tag/neuvector-vulnerability-scanner-1.11

[#_rancher_catalog_updates_january_2021]
=== Rancher Catalog Updates January 2021

* Update {product-name} in Rancher catalog to support 4.x

[#_helm_chart_updates_january_2021]
=== Helm Chart Updates January 2021

* Create required {product-name} CRDs upon deployment
* Fix error when setting controller ingress to true

[#_operator_updates_january_2021]
=== Operator Updates January 2021

* Update Operators (community, certified) to support 4.x

[#_helm_chart_changes_december_2020]
=== Helm Chart Changes December 2020

* Allow user to customize PriorityClass of the manager/controller/enforcer/scanner deployment. We suggest to give {product-name} containers higher priority to make sure the security policies get enforced when the node resource is under pressure or during a cluster upgrade process.

[#_important_helm_chart_update_november_2020]
=== Important Helm Chart Update November 2020

[IMPORTANT]
====
Changes to Helm Chart Structure
====

* The directory for the {product-name} chart has changed from ./neuvector-helm/ to ./neuvector-helm/charts/core/

If using Helm to upgrade, please update the location to the path above.
