= Restoring {product-name} Configuration
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /02.deploying/11.restore/11.restore.md
:page-opendocs-slug: /deploying/restore

== Restoring {product-name} Configuration

A backup of the {product-name} configuration can be applied to restore a previous configuration of {product-name}. The backup file can be generated manually as well as imported from the console in Settings -> Configuration, choosing all configuration (e.g. registry configurations, integrations, other settings plus policy) or Policy only (e.g. rules/security policy). The rest API can also be used to automatically backup the configuration, as seen in this xref:automation.adoc#_exportimport_configuration_file[example].

Cluster events where all controllers stop running, thereby losing real-time configuration state, can be automatically restored when xref:production.adoc#_backups_and_persistent_data[persistent storage] has been properly configured.

[NOTE]
====
{product-name} does not support partial restoration of objects (e.g. network rules only) nor timestamped restoration (e.g. restore from date/time snapshots). Please use xref:automation.adoc#_exportimport_configuration_file[automation scripts] to regularly backup configuration files and manage timestamps.
====

[CAUTION]
====
The backup configuration files should not be edited in any way. Any changes to these from their exported state could result in restoration errors and an unpredictable result.
====

[IMPORTANT]
====
Backup configuration files should be used to restore a {product-name} state on the same cluster from which they were exported. Applying a backup configuration file from a different cluster could result in unpredictable results.
====

=== Recommended High Availability Settings

Manual backup and restore of configuration should be planned only as a last resort. The following steps are recommended for high availability.

. Use Helm with a ConfigMap for initial deployment and configuration.
. Use CRDs for defining policy such as network/process, admission control, and other rules.
. Run multiple controllers (minimum 3) to auto-sync configuration between running pods, and ensure they run on different hosts.
. Configure persistent storage (as part of step 1) to recover from any cluster wide failures where all controllers stop running.
. Regularly backup configuration to timestamped backup files.
. Restore a cluster's {product-name} configuration from a backup file as a last resort, applying any CRDs after restoration that were new or changed since the previous backup.
