= 一般ガイドライン
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /13.special/01.general/01.general.md
:page-opendocs-slug:  /special/general

== {product-name}Allinoneコンテナを使用したテスト

このセクションの例は、AllinoneおよびEnforcerコンテナのデプロイ方法を示しています。このセットアップは、{product-name}Kubernetes以外の環境でをテストするのに役立ちます。Kubernetesデプロイメントの場合は、最新の{product-name} Helmチャートを使用してください。詳細については、xref:./production.adoc[デプロイメントの計画]を参照してください。

[IMPORTANT]
====
チームは、{product-name}このセットアップを本番環境で使用することを強く非推奨としています。また、本番環境での使用はサポートされていません。
====

== デプロイメントの一般的なガイドライン

適切なインストールのためにホスト環境を準備してください。コンテナ{product-name}がホスト間で相互に通信できることを確認してください。次に、ご自身の環境に合わせてサンプルファイルを確認し、編集してください。

一般的に、以下のことを行うことが重要です：

. ノードに適切なラベルを付けてください。allinoneまたはコントローラーがデプロイされる場所を制御するためにノードラベルを使用する場合は、デプロイする前にラベルを付けてください。
. ボリュームが適切にマッピングできることを確認してください。次に例を示します。
+
[,yaml]
----
volumes:
        - /var/neuvector:/var/neuvector
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc:/host/proc:ro
        - /sys/fs/cgroup:/host/cgroup:ro
----

. ホストで必要なポートを開いてください。必要なポートが適切にマッピングされ、ホストで開いていることを確認してください。allinoneは8443（コンソールを使用する場合）、18300、18301、18400、および18401を必要とします。Enforcerは18301および18401を必要とします。
. CLUSTER_JOIN_ADDRを編集してください。ノードのIPアドレス、ノード名（ネームサーバを使用している場合）またはノード変数（オーケストレーションツールを使用している場合）を特定し、これらの情報を、サンプルファイル中でallinone（またはコントローラー）およびenforcerの"`node IP`"に利用してください。

== コンソールにアクセスする

最初のセクション「基本」->「マネージャーに接続」では、httpsをオフにするオプションや、ポート8443を許可しない企業ファイアウォールを通じてコンソールにアクセスする方法について説明しています。
