= 統合とその他のコンポーネント
:revdate: 2024-09-27
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/02.other/02.other.md
:page-opendocs-slug:  /releasenotes/other

== 統合モジュール、プラグイン、その他のコンポーネントのリリースノート

=== GitHub Actions

* 脆弱性スキャンのためのGitHub Actionsが https://github.com/neuvector/neuvector-image-scan-action.に公開されました

=== Helmチャート 1.8.9

* Helmチャートv1.8.9は5.0.0のデプロイメント用に公開されています。5.0.0のプレビュー版を使用する場合、values.ymlに以下の変更を加える必要があります：
** レジストリをdocker.ioに更新する
** Docker Hubのプレビュー版に合わせてイメージ名/タグを更新する
** imagePullSecretsを空のままにする

=== Splunkアプリが公開されました

* {product-name}の新しいSplunkアプリが https://splunkbase.splunk.com/app/6205/に公開されました

=== Helmチャートの更新 1.8.7

* コントローラー、スキャナー、マネージャーのためのアフィニティとトレランスのカスタマイズをサポートします。
* コントローラー、マネージャー、スキャナー、アップデーターのポッドに対するnodeSelectorのサポートを追加します。
* コントローラーコンテナのためのユーザー定義の環境変数をサポートします。

=== Helmチャート 1.8.2のためのコミュニティオペレーターv1.2.7

* ユーザーが{product-name}のリリースバージョンを指定できるようにします
* 最新のスキャナーCVEデータベースバージョンをデプロイします
* コンテナオペレーターのイメージの場所がregistry.neuvector.com/publicに移動しました
* {product-name} インスタンス名はneuvectorにデフォルト設定されています（以前はexample-neuvectorでした）
* インストールページのreadmeドキュメントを更新し、リリースノートへのリンクを追加しました

=== Helmチャート 1.8.2

* コントローラーのイングレスとルートホストオプションを追加しました。

=== {product-name} v4.3.1用の認定オペレーター v1.2.8

* Helmチャートバージョン1.8.2をサポートしています
* {product-name} バージョン4.3.1をデプロイします
* スキャナーデータベースバージョン2.360をデプロイします
* 以前の1.2.7バージョンからのその他の変更
** neuvectorインスタンス名はneuvectorにデフォルト設定されています。以前はexample-neuvectorでした
** インストールページのreadmeドキュメントを更新しました
** {product-name} ロゴの表示問題を修正しました
* 当バージョンの注意事項
** 1.2.7から1.2.8にアップグレードしてもスキャナーデータベースはアップグレードされません。作業回避策：スキャナーのデプロイメントでスキャナーイメージをregistry.connect.redhat.com/neuvector/scanner@sha256:a802c012eee80444d9deea8c4402a1d977cf57d7b2b2044f90c9acc0e7ca3e06に更新してください。
** インストールページのreadmeドキュメントが正しく整列されていません
** スキャナーデータベースはアップデーターによって更新されません

=== Helmチャート更新 1.8.0（2021年7月）

* Helmチャート v1.8.0は、registry.neuvector.comをデフォルトのレジストリとして使用するように更新されました。NOTE:バージョンタグを手動で指定する必要があります。
* HelmチャートにコントローラーAPIの注釈などの構成可能なパラメータを追加します。バージョン1.7.6以上で利用可能です。
* Community Operator 1.2.6、Certified Operator 1.2.7は、controller.apisvc.typeが有効な場合にOpenShiftルートを追加するなど、Helmチャートの更新を反映するように更新されました。

=== 他の統合 2021年7月

* Jenkinsパイプラインスキャン結果におけるスキャン結果のHTML出力形式を追加します。
* Prometheusエクスポータアラートに影響を受けるワークロードのネームスペースを追加します。現在、neuvector/prometheus-exporter:4.2.2以降でサポートされています。

=== Helmチャート更新 1.7.5（2021年5月）

* 新しいイメージレジストリ registry.neuvector.com に必要な変更をサポートします。 これに変更すると、イメージパスが変更されます（つまり、neuvector/controllerからcontrollerへのパスでneuvectorが削除されます）。

=== Helmチャート更新 1.7.2（2021年4月）

* コントローラー、エンフォーサーのCPU、メモリリソース要求など、別々のコンポーネントリソースのリクエストと制限をサポートします。

=== Jenkinsプラグイン更新 v1.13（2021年4月）

* 複数のスキャナーが同時に実行されているときに存在するスキャンエラーを修正します。
* Red Hatベースのイメージのスキャン結果にRed Hatの脆弱性評価を表示します。

=== オペレーター更新（2021年4月）

* OpenShiftオペレーター/Helmは自己署名証明書を置き換えることができるようになります。Helmチャートは1.7.1です。Community Operatorは1.2.4、Certified Operatorは1.2.3です。

=== Jenkinsプラグイン v1.12（2021年3月）

* スコアによって脆弱性の深刻度を上書きします。脆弱性（CVE）スコア範囲を高および中の分類に使用するように編集できるようにします。これにより、パイプライン内でビルドを失敗させるために使用できるスコアをカスタマイズできます。
* JAVA例外hudson.AbortExceptionにエラーメッセージを追加します。エラーが発生した際に{product-name}からのエラーメッセージ報告を改善します。

=== Helmチャートを1.7.1（2021年3月）に更新します。

* マネージャサービスのロードバランサーIPと注釈を追加します。
* PVC容量を設定するための設定を追加します。
* k3sおよびAWS Bottlerocketのためのランタイムソケット設定を追加します。
* コントローラーおよびマネージャ証明書を置き換えるための設定を追加します。

=== スキャナー 2021年2月

* スキャナーのバージョン1.191およびそれ以前でスキャン中に発見されなかったCVE-2020-1938を修正します。1.191以降の最新のスキャナー バージョンに更新します。

=== Jenkinsプラグインv1.11 2021年2月

==== 拡張機能

* スタンドアロンの{product-name}スキャナーをデプロイすることをサポートします。これにはコントローラーは必要なく、Jenkinsインストールと同じホストにデプロイする必要があります。ホストにもDockerをインストールする必要があります。現在、JenkinsのLinuxバージョンのみがサポートされています（コンテナバージョンではありません）。また、_jenkins_ユーザーを_docker_グループに追加します。

[,bash]
----
sudo usermod -aG docker jenkins
----

参考資料：
https://plugins.jenkins.io/neuvector-vulnerability-scanner/
https://github.com/jenkinsci/neuvector-vulnerability-scanner-plugin/releases/tag/neuvector-vulnerability-scanner-1.11

=== Rancherカタログの更新 2021年1月

* Rancher カタログの {product-name} を 4.x に対応するように更新します。

=== Helm チャートの更新 2021年1月

* デプロイ時に必要な {product-name} CRD を作成します。
* コントローラーの Ingress を true に設定する際のエラーを修正します。

=== オペレーターの更新 2021年1月

* オペレーター（コミュニティ、認定）の 4.x 対応を更新します。

=== Helm チャートの変更 2020年12月

* ユーザーがマネージャー/コントローラー/エンフォーサー/スキャナーのデプロイメントの PriorityClass をカスタマイズできるようにします。ノードリソースが圧迫されている場合や、クラスターのアップグレード中にセキュリティポリシーが確実に適用されるよう、{product-name}コンテナに高い優先度を付与することをお勧めします。

=== 重要な Helm チャートの更新 2020年11月

[IMPORTANT]
====
Helm チャート構造の変更
====

* {product-name} チャートのディレクトリが ./neuvector-helm/ から ./neuvector-helm/charts/core/ に変更されました。

Helm を使用してアップグレードする場合は、上記のパスに更新してください。
